eureka:
  client:
    use-dns-for-fetching-service-urls: true
    region: cn-guangzhou
    eureka-server-d-n-s-name: ebox
    eureka-server-port: ${server.port}
    eureka-server-u-r-l-context: eureka
    fetch-registry: false
server:
  port: 8761
logging:
  file: /var/log/${spring.application.name}/info.log